ALTER TABLE public.clientes 
ADD COLUMN IF NOT EXISTS rg TEXT,
ADD COLUMN IF NOT EXISTS estado_civil TEXT,
ADD COLUMN IF NOT EXISTS nacionalidade TEXT,
ADD COLUMN IF NOT EXISTS data_nascimento DATE;

ALTER TABLE public.veiculos
ADD COLUMN IF NOT EXISTS valor_venda NUMERIC DEFAULT 0;